load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_python//python:py_library.bzl", "py_library")

package(default_visibility = ["//visibility:private"])

py_library(
    name = "package",
    srcs = ["__init__.py"],
    visibility = ["//bazel/lint:__pkg__"],
)

py_binary(
    name = "source_stamp_generator",
    srcs = ["source_stamp_generator.py"],
    legacy_create_init = 0,
    main = "source_stamp_generator.py",
    python_version = "3.13",
    visibility = ["//visibility:private"],
)

py_binary(
    name = "test_standalone_runfiles_marker",
    srcs = ["test_standalone_runfiles_marker.py"],
    legacy_create_init = 0,
    main = "test_standalone_runfiles_marker.py",
    python_version = "3.13",
    visibility = ["//:__pkg__"],
)
